const instaListContract = {};
instaListContract.address = '0x4c8a1BEb8a87765788946D6B19C6C6355194AbEb';
instaListContract.abi = [
    {
       "inputs":[
          {
             "internalType":"uint64",
             "name":"",
             "type":"uint64"
          }
       ],
       "name":"accountAddr",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "name":"accountID",
       "outputs":[
          {
             "internalType":"uint64",
             "name":"",
             "type":"uint64"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint64",
             "name":"",
             "type":"uint64"
          }
       ],
       "name":"accountLink",
       "outputs":[
          {
             "internalType":"address",
             "name":"first",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"last",
             "type":"address"
          },
          {
             "internalType":"uint64",
             "name":"count",
             "type":"uint64"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"uint64",
             "name":"",
             "type":"uint64"
          },
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "name":"accountList",
       "outputs":[
          {
             "internalType":"address",
             "name":"prev",
             "type":"address"
          },
          {
             "internalType":"address",
             "name":"next",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
 
       ],
       "name":"accounts",
       "outputs":[
          {
             "internalType":"uint64",
             "name":"",
             "type":"uint64"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_owner",
             "type":"address"
          }
       ],
       "name":"addAuth",
       "outputs":[
 
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_account",
             "type":"address"
          }
       ],
       "name":"init",
       "outputs":[
 
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
 
       ],
       "name":"instaIndex",
       "outputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"_owner",
             "type":"address"
          }
       ],
       "name":"removeAuth",
       "outputs":[
 
       ],
       "stateMutability":"nonpayable",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          }
       ],
       "name":"userLink",
       "outputs":[
          {
             "internalType":"uint64",
             "name":"first",
             "type":"uint64"
          },
          {
             "internalType":"uint64",
             "name":"last",
             "type":"uint64"
          },
          {
             "internalType":"uint64",
             "name":"count",
             "type":"uint64"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    },
    {
       "inputs":[
          {
             "internalType":"address",
             "name":"",
             "type":"address"
          },
          {
             "internalType":"uint64",
             "name":"",
             "type":"uint64"
          }
       ],
       "name":"userList",
       "outputs":[
          {
             "internalType":"uint64",
             "name":"prev",
             "type":"uint64"
          },
          {
             "internalType":"uint64",
             "name":"next",
             "type":"uint64"
          }
       ],
       "stateMutability":"view",
       "type":"function"
    }
];

const instaEventContract = {};
instaEventContract.address = '0x2af7ea6Cb911035f3eb1ED895Cb6692C39ecbA97';
instaEventContract.abi = [
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint64",
            "name":"connectorType",
            "type":"uint64"
         },
         {
            "indexed":true,
            "internalType":"uint64",
            "name":"connectorID",
            "type":"uint64"
         },
         {
            "indexed":true,
            "internalType":"uint64",
            "name":"accountID",
            "type":"uint64"
         },
         {
            "indexed":true,
            "internalType":"bytes32",
            "name":"eventCode",
            "type":"bytes32"
         },
         {
            "indexed":false,
            "internalType":"bytes",
            "name":"eventData",
            "type":"bytes"
         }
      ],
      "name":"LogEvent",
      "type":"event"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_connectorType",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_connectorID",
            "type":"uint256"
         },
         {
            "internalType":"bytes32",
            "name":"_eventCode",
            "type":"bytes32"
         },
         {
            "internalType":"bytes",
            "name":"_eventData",
            "type":"bytes"
         }
      ],
      "name":"emitEvent",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[

      ],
      "name":"instaList",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   }
];

const instaIndexContract = {};
instaIndexContract.address = '0x2971AdFa57b20E5a416aE5a708A8655A9c74f723';
instaIndexContract.abi = [
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"address",
            "name":"sender",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"account",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"origin",
            "type":"address"
         }
      ],
      "name":"LogAccountCreated",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_newAccount",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"_connectors",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"_check",
            "type":"address"
         }
      ],
      "name":"LogNewAccount",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"uint256",
            "name":"accountVersion",
            "type":"uint256"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"check",
            "type":"address"
         }
      ],
      "name":"LogNewCheck",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"master",
            "type":"address"
         }
      ],
      "name":"LogNewMaster",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"master",
            "type":"address"
         }
      ],
      "name":"LogUpdateMaster",
      "type":"event"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"account",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_newAccount",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_connectors",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_check",
            "type":"address"
         }
      ],
      "name":"addNewAccount",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_owner",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"accountVersion",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"_origin",
            "type":"address"
         }
      ],
      "name":"build",
      "outputs":[
         {
            "internalType":"address",
            "name":"_account",
            "type":"address"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_owner",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"accountVersion",
            "type":"uint256"
         },
         {
            "internalType":"address[]",
            "name":"_targets",
            "type":"address[]"
         },
         {
            "internalType":"bytes[]",
            "name":"_datas",
            "type":"bytes[]"
         },
         {
            "internalType":"address",
            "name":"_origin",
            "type":"address"
         }
      ],
      "name":"buildWithCast",
      "outputs":[
         {
            "internalType":"address",
            "name":"_account",
            "type":"address"
         }
      ],
      "stateMutability":"payable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"accountVersion",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"_newCheck",
            "type":"address"
         }
      ],
      "name":"changeCheck",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_newMaster",
            "type":"address"
         }
      ],
      "name":"changeMaster",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"check",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"connectors",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"version",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"query",
            "type":"address"
         }
      ],
      "name":"isClone",
      "outputs":[
         {
            "internalType":"bool",
            "name":"result",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[

      ],
      "name":"list",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[

      ],
      "name":"master",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_master",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_list",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_account",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_connectors",
            "type":"address"
         }
      ],
      "name":"setBasics",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[

      ],
      "name":"updateMaster",
      "outputs":[

      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[

      ],
      "name":"versionCount",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   }
];

module.exports = { instaListContract, instaEventContract, instaIndexContract };